/**
 * 进行定义请求Action类型
 */
'use strict';

//微信精选
export const ACTION_WX_NEWS_PRE_FETCH = 'ACTION_WX_NEWS_PRE_FETCH';
export const ACTION_WX_NEWS_FETCH_OK = 'ACTION_WX_NEWS_FETCH_OK';
export const ACTION_WX_NEWS_FETCH_ERROR = 'ACTION_WX_NEWS_FETCH_ERROR';

//Home页top banner
export const ACTION_HOME_BANNER_FETCHED = 'ACTION_HOME_BANNER_FETCHED';





export const ACTION_MAIN_RECEIVED_CONFIG = 'ACTION_MAIN_RECEIVED_CONFIG';
export const ACTION_MAIN_RECEIVED_RECOMMAND = 'ACTION_MAIN_RECEIVED_RECOMMAND';

export const ACTION_RECOMMAND_LIST_LOADING_MORE = 'ACTION_RECOMMAND_LIST_LOADING_MORE';
export const ACTION_RECOMMAND_LIST_RECEIVED = 'ACTION_RECOMMAND_LIST_RECEIVED';

export const ACTION_TEMPLATE_LIST_START_LOAD = 'ACTION_TEMPLATE_LIST_START_LOAD';
export const ACTION_TEMPLATE_LIST_RECEIVED = 'ACTION_TEMPLATE_LIST_RECEIVED';

export const ACTION_RECEIVED_ACCOUNT_CREDITS = 'ACTION_RECEIVED_ACCOUNT_CREDITS';
export const ACTION_GOOGLE_PAY_INITED = 'ACTION_GOOGLE_PAY_INITED';
export const ACTION_CHARGE_GET_ACCOUNT = 'ACTION_CHARGE_GET_ACCOUNT';

export const ACTION_USE_TEMPLATE_LOADING = 'ACTION_USE_TEMPLATE_LOADING';
export const ACTION_USE_TEMPLATE_RECHARGE = 'ACTION_USE_TEMPLATE_RECHARGE';
export const ACTION_USE_TEMPLATE_PURCHASE = 'ACTION_USE_TEMPLATE_PURCHASE';
export const ACTION_USE_TEMPLATE_GET_ACCOUNT = 'ACTION_USE_TEMPLATE_GET_ACCOUNT';

export const ACTION_MINE_ACCOUNT_CREDITS = 'ACTION_MINE_ACCOUNT_CREDITS';
export const ACTION_MINE_GET_ACCOUNT = 'ACTION_MINE_GET_ACCOUNT';
export const ACTION_MINE_GET_TEMPLATES = 'ACTION_MINE_GET_TEMPLATES';
export const ACTION_MINE_GET_PURCHASES = 'ACTION_MINE_GET_PURCHASES';